---
- name: "Reload sshd using systemd"
  ansible.builtin.systemd:
    name: "sshd"
    state: "reloaded"
  when: "ansible_facts['service_mgr'] == 'systemd'"
  listen: "reload sshd"

- name: "Reload sshd using runit"
  community.general.runit:
    name: "sshd"
    state: "reloaded"
  when: "ansible_facts['service_mgr'] == 'runit'"
  listen: "reload sshd"

- name: "Restart sshd using dinit"
  ansible.builtin.command:
    argv:
      - dinitctl
      - --system
      - restart
      - sshd
  changed_when: true
  when: ansible_facts['os_family'] in ["Chimera"]
  listen: "reload sshd"
