---
ssh_config_file: "/etc/ssh/sshd_config"

ssh_preset: "{{ ssh_secure_presets }}"
ssh_loglevel: "VERBOSE"
ssh_address_family: "any"

ssh_password_authentication: false
ssh_challenge_response_authentication: false
ssh_pubkey_authentication: true
ssh_root_login: false
ssh_client_alive_interval: 300
ssh_protocol: 2
ssh_x11_forwarding: false
ssh_allow_agent_forwarding: false
ssh_allow_tcp_forwarding: false
