---
- name: "No-op task for defining a yaml anchor"
  ansible.builtin.meta: "noop"
  vars: &sshd_config_args
    path: "{{ sshd_config_file }}"
    state: "present"
    validate: "sshd -Tf %s"
  tags: ["prepare", "prepare-sshd"]

- name: "Disallow password authentication"
  ansible.builtin.lineinfile:
    <<: *sshd_config_args
    regexp: "^#?PasswordAuthentication"
    line: "PasswordAuthentication {{ sshd_config_password_authentication | ternary('yes', 'no') }}"
  notify: "reload sshd"
  tags: ["prepare", "prepare-sshd"]

- name: "Disallow challenge-response authentication"
  ansible.builtin.lineinfile:
    <<: *sshd_config_args
    regexp: "^#?ChallengeResponseAuthentication"
    line: "ChallengeResponseAuthentication {{ sshd_config_challenge_response_authentication | ternary('yes', 'no') }}"
  notify: "reload sshd"
  tags: ["prepare", "prepare-sshd"]

- name: "Allow pubkey authentication"
  ansible.builtin.lineinfile:
    <<: *sshd_config_args
    regexp: "^#?PubkeyAuthentication"
    line: "PubkeyAuthentication {{ sshd_config_pubkey_authentication | ternary('yes', 'no') }}"
    firstmatch: true
  notify: "reload sshd"
  tags: ["prepare", "prepare-sshd"]

- name: "Disallow root login"
  ansible.builtin.lineinfile:
    <<: *sshd_config_args
    regexp: "^#?PermitRootLogin"
    line: "PermitRootLogin {{ sshd_config_root_login | ternary('yes', 'no') }}"
  notify: "reload sshd"
  tags: ["prepare", "prepare-sshd"]

- name: "Do not allow sessions to idle longer than 5 minutes"
  ansible.builtin.lineinfile:
    <<: *sshd_config_args
    regexp: "^#?ClientAliveInterval"
    line: "ClientAliveInterval {{ sshd_config_client_alive_interval }}"
  notify: "reload sshd"
  tags: ["prepare", "prepare-sshd"]

- name: "Set maximum number of open sessions permitted per network connection"
  ansible.builtin.lineinfile:
    <<: *sshd_config_args
    regexp: "^#?MaxSessions"
    line: "MaxSessions {{ sshd_config_max_sessions }}"
  when: "sshd_config_max_sessions is defined"
  notify: "reload sshd"
  tags: ["prepare", "prepare-sshd"]

- name: "Unset maximum number of open sessions permitted per network connection"
  ansible.builtin.lineinfile:
    <<: *sshd_config_args
    regexp: "^#?MaxSessions"
    line: "#MaxSessions 10"
  when: "sshd_config_max_sessions is not defined"
  notify: "reload sshd"
  tags: ["prepare", "prepare-sshd"]

- name: "Set maximum number of concurrent unauthenticated connections"
  ansible.builtin.lineinfile:
    <<: *sshd_config_args
    regexp: "^#?MaxStartups"
    line: "MaxStartups {{ sshd_config_max_startups }}"
  when: "sshd_config_max_startups is defined"
  notify: "reload sshd"
  tags: ["prepare", "prepare-sshd"]

- name: "Unset maximum number of concurrent unauthenticated connections"
  ansible.builtin.lineinfile:
    <<: *sshd_config_args
    regexp: "^#?MaxStartups"
    line: "#MaxStartups 10:30:100"
  when: "sshd_config_max_startups is not defined"
  notify: "reload sshd"
  tags: ["prepare", "prepare-sshd"]

- name: "Only allow SSHv2"
  ansible.builtin.lineinfile:
    <<: *sshd_config_args
    regexp: "^#?Protocol"
    line: "Protocol {{ sshd_config_protocol }}"
    insertafter: &cipher_after ^# Ciphers and keying
  notify: "reload sshd"
  tags: ["prepare", "prepare-sshd"]

- name: "Disallow X11-Forwarding"
  ansible.builtin.lineinfile:
    <<: *sshd_config_args
    regexp: "^#?X11Forwarding"
    line: "X11Forwarding {{ sshd_config_x11_forwarding | ternary('yes', 'no') }}"
  notify: "reload sshd"
  tags: ["prepare", "prepare-sshd"]

- name: "Disallow Agent Forwarding"
  ansible.builtin.lineinfile:
    <<: *sshd_config_args
    regexp: "^#?AllowAgentForwarding"
    line: "AllowAgentForwarding {{ sshd_config_allow_agent_forwarding | ternary('yes', 'no') }}"
  notify: "reload sshd"
  tags: ["prepare", "prepare-sshd"]

- name: "Disallow TCP Forwarding"
  ansible.builtin.lineinfile:
    <<: *sshd_config_args
    regexp: "^#?AllowTcpForwarding"
    line: "AllowTcpForwarding {{ sshd_config_allow_tcp_forwarding | ternary('yes', 'no') }}"
  notify: "reload sshd"
  tags: ["prepare", "prepare-sshd"]

- name: "Query supported KexAlgorithms"
  ansible.builtin.command:
    argv:
      - ssh
      - -Q
      - KexAlgorithms
  changed_when: false
  check_mode: false
  when: "sshd_preset.allowed_kexalgos is defined"
  register: sshd_queried_kex_algorithms
  tags: ["prepare", "prepare-sshd"]

- name: "Only allow reasonably secure KexAlgorithms"
  ansible.builtin.lineinfile:
    <<: *sshd_config_args
    regexp: "^#?KexAlgorithms"
    line: "KexAlgorithms {{ sshd_preset.allowed_kexalgos | famedly.base.intersect(sshd_queried_kex_algorithms.stdout_lines) | join(',') }}"
    insertafter: *cipher_after
  when: "sshd_preset.allowed_kexalgos is defined"
  notify: "reload sshd"
  tags: ["prepare", "prepare-sshd"]

- name: "Query supported Ciphers"
  ansible.builtin.command:
    argv:
      - ssh
      - -Q
      - Ciphers
  changed_when: false
  check_mode: false
  when: "sshd_preset.allowed_ciphers is defined"
  register: sshd_queried_ciphers
  tags: ["prepare", "prepare-sshd"]

- name: "Only allow reasonably secure Ciphers"
  ansible.builtin.lineinfile:
    <<: *sshd_config_args
    regexp: "^#?Ciphers"
    line: "Ciphers {{ sshd_preset.allowed_ciphers | famedly.base.intersect(sshd_queried_ciphers.stdout_lines) | join(',') }}"
    insertafter: *cipher_after
  when: "sshd_preset.allowed_ciphers is defined"
  notify: "reload sshd"
  tags: ["prepare", "prepare-sshd"]

- name: "Query supported MACs"
  ansible.builtin.command:
    argv:
      - ssh
      - -Q
      - MACs
  changed_when: false
  check_mode: false
  when: "sshd_preset.allowed_macs is defined"
  register: sshd_queried_macs
  tags: ["prepare", "prepare-sshd"]

- name: "Only allow reasonably secure MACs"
  ansible.builtin.lineinfile:
    <<: *sshd_config_args
    regexp: "^#?MACs"
    line: "MACs {{ sshd_preset.allowed_macs | famedly.base.intersect(sshd_queried_macs.stdout_lines) | join(',') }}"
    insertafter: *cipher_after
  when: "sshd_preset.allowed_macs is defined"
  notify: "reload sshd"
  tags: ["prepare", "prepare-sshd"]

- name: "Query supported HostKeyAlgorithms"
  ansible.builtin.command:
    argv:
      - ssh
      - -Q
      - HostKeyAlgorithms
  changed_when: false
  check_mode: false
  when: "sshd_preset.allowed_hostkey_algos is defined"
  register: sshd_queried_hostkey_algos
  tags: ["prepare", "prepare-sshd"]

- name: "Only allow reasonably secure HostKeyAlgorithms"
  ansible.builtin.lineinfile:
    <<: *sshd_config_args
    regexp: "^#?HostKeyAlgorithms"
    line: "HostKeyAlgorithms {{ sshd_preset.allowed_hostkey_algos | famedly.base.intersect(sshd_queried_hostkey_algos.stdout_lines) | join(',') }}"
    insertafter: *cipher_after
  when: "sshd_preset.allowed_hostkey_algos is defined"
  notify: "reload sshd"
  tags: ["prepare", "prepare-sshd"]

- name: "Query supported PubkeyAcceptedKeyTypes"
  ansible.builtin.command:
    argv:
      - ssh
      - -Q
      - PubkeyAcceptedKeyTypes
  changed_when: false
  check_mode: false
  when: "sshd_preset.allowed_pubkey_algos is defined"
  register: sshd_queried_pubkey_algos
  tags: ["prepare", "prepare-sshd"]

- name: "Only allow reasonably secure PubkeyAcceptedKeyTypes"
  ansible.builtin.lineinfile:
    <<: *sshd_config_args
    regexp: "^#?PubkeyAcceptedKeyTypes"
    line: "PubkeyAcceptedKeyTypes {{ sshd_preset.allowed_pubkey_algos | famedly.base.intersect(sshd_queried_pubkey_algos.stdout_lines) | join(',') }}"
    insertafter: *cipher_after
  when: "sshd_preset.allowed_pubkey_algos is defined"
  notify: "reload sshd"
  tags: ["prepare", "prepare-sshd"]

- name: "Set LogLevel to {{ sshd_loglevel }}"
  ansible.builtin.lineinfile:
    <<: *sshd_config_args
    regexp: "^#?LogLevel"
    line: "LogLevel {{ sshd_loglevel }}"
  notify: "reload sshd"
  tags: ["prepare", "prepare-sshd"]

- name: "Listen on address family {{ sshd_address_family }}"
  ansible.builtin.lineinfile:
    <<: *sshd_config_args
    regexp: "^#?AddressFamily"
    line: "AddressFamily {{ sshd_address_family }}"
  notify: "reload sshd"
  tags: ["prepare", "prepare-sshd"]
